#!/bin/bash

# returns:
#   0: yes
#   1: no
#   2: default
#   *: exit
# examples:
# option `test -f ~/.vimrc && test -f ~/.tmux.conf` "~/.vimrc of ~/.tmux.conf already exists" "continue [Y,n]"
# option `hash tmuxp 2>/dev/null` "tmuxp not installed" "continue [y,N]"
option () {
    if [ $? != 0 ]; then
        echo $1
        echo -n "$2 "
        read -n 1 op
        if [ "$op" != "" ]; then echo; fi
        case $op in
            "y") return 0 ;;
            "Y") return 0 ;;
            "n") return 1 ;;
            "N") return 1 ;;
            "") return 2; ;;
            *) echo "invalid option"; exit 1 ;;
        esac
    fi
    return 0
}

option_stop () {
    option $? "$1" "continue [y,N]"
    if [ $? != 0 ]; then exit; fi
}

option_skip () {
    option "$1" "skip [Y,n]"
    if [ $? == 1 ]; then exit; fi
    return 2
}

install_bash () {
    grep -e "^source ~/.dotfiles/bashrc$" ~/.bashrc >/dev/null 2>/dev/null
    test $? == 1
    option_skip "Already exists bashrc in your ~/.bashrc"
    if [ $? == 2 ]; then
        return 0;
    fi
	echo "source ~/.dotfiles/bashrc" >> ~/.bashrc
	echo ". ~/.bashrc" >> ~/.bash_profile
}

install_tmux () {
    option_stop `hash tmuxp 2>/dev/null` "tmuxp not found"

    ls ~/.tmuxp 2>/dev/null
    if [ $? != 0 ]; then
        ln -sfv ~/Dropbox/tmuxp ~/.tmuxp
    fi


	ln -sfv ~/.dotfiles/tmux.conf ~/.tmux.conf
    test ! -f ~/.tmux-local.conf
    option_skip "~/.tmux-local.conf already exists"
    if [ $? == 2 ]; then
        return 0;
    fi
	>> ~/.tmux-local.conf
}

install_yaourt () {
	ln -sv ~/.dotfiles/yaourtrc ~/.yaourtrc
}

install_vim () {
	ln -sv ~/.dotfiles/vimrc ~/.vimrc
	vim +PluginInstall +qall
}

install_yaourt () {
	ln -sfv ~/.dotfiles/yaourtrc ~/.yaourtrc
}

case $1 in
	"bash") install_bash ;;
	"tmux") install_tmux ;;
	"yaourt") install_yaourt ;;
	"vim") install_vim ;;
	*)
		install_bash
		install_tmux
		install_yaourt
		install_vim
		;;
esac
